import { initializePostgresDatabase } from '@sessions/web-db';
import { ThemeProvider } from 'next-themes';

import './global.css';
import { env } from '../env';

export const metadata = {
  title: 'Welcome to apps/web',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await initDb();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}

function initDb() {
  return initializePostgresDatabase(
    {
      host: env.server.POSTGRES_HOST,
      port: +env.server.POSTGRES_PORT, // TODO? Do better. Zod transform?
      username: env.server.POSTGRES_USER,
      password: env.server.POSTGRES_PASSWORD,
      database: env.server.POSTGRES_DB,
    },
    '../../../libs/web/db/migrations',
  );
}
